# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 362e7c91107cc5da8b4e5940ad626b9d14fc968c246b49dda663c86152d680c56322c007db8c55a1b82e48bc858c714fcc92655a8953fedfa112fcded6c045da

test:
  secret_key_base: 3a8d61e9485864a6b9d75f22be338a229fa7b3cdc02f10689f6f70ab63b4d33af48deb09c15ddd336c4fa2253458d66e40c4ad845c2a74ba98a10c6d03c5a9ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
